#!/usr/bin/env bash
# This script installs nginx on web-01 server
# Listening on port 80
# Returns string Hello World when queried at root

sudo apt-get -y update
sudo apt-get -u upgrade
sudo apt-get -y install nginx
sudo rm /var/www/html/*.html
sudo echo "Hello World" | sudo tee /var/www/html/index.html 
