#!/usr/bin/env bash
#This script displays superstitious numbers
i=0
while ((i < 20))
do
    i=$((i + 1))
    echo $i
    case $i in
	4)
	    echo 'bad luck from China'
	    ;;
	9)
	    echo 'bad luck from Japan'
	    ;;
	17)
	    echo 'bad luck from Italy'
	    ;;
	esac
done
