#!/usr/bin/env bash
# This script transfers a file from client to server
# This script accepts 4 parameters
# 1. The path to the file to be transferred
# 2. The IP of the server we want to transfer the file to
# 3. The username 'scp' connects with
# 4. The path to the SSH private key that 'scp' uses
# Display Usage: 0-transfer_File PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters are passed

if [ $# -ne 4 ];
    then echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO SSH KEY"
else
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi