#!/usr/bin/env bash
# This script installs and configures HAproxy load balancer
# HAproxy will send traffic to 4905-web-01 and 4905-web-02
# Requests will be distributed using round robin algorithm

config_frontend="frontend\n\tfrontend main\n\tbind *:80\n\tdefault_backend web_servers\n"
config_backend="backend\n\tbackend web_servers\n\tbalance roundrobin\n\tserver 4905-web-01 3.93.184.123\n\tserver 4905-web-02 54.211.211.168\n"

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo ENABLED=1 | sudo tee -a /etc/default/haproxy
echo -e "$config_frontend"+"$config_backend" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start